# https://golang.github.io/dep/docs/Gopkg.toml.html

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

[[constraint]]
  branch = "master"
  name = "github.com/alexflint/go-arg"

[[constraint]]
  name = "github.com/go-chi/chi"
  version = "3.3.0"

[[constraint]]
  name = "github.com/go-chi/render"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/minio/minio-go"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/afero"
